name: Run Tests

on: [push, workflow_dispatch]

jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Flutter
      uses: subosito/flutter-action@v1
    - name: Set up API keys
      run: echo "API_KEY=${{ secrets.API_KEY }}" > .env
    - run: flutter test
