name: Run Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create api_keys.dart
        run: echo "const apiKey = '${{ secrets.API_KEY }}';" > lib/src/api/api_keys.dart

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
